[BugFix][List] Fix sticky-offset parse error
UIListContainer should not use ListEventManager#dynamicToInt method to parse value because ListEventManager is extend RecyclerView.OnScrollListener which may lead to NoClassDefFoundError.

issue: m-6796064504